# Generated by Django 4.2.8 on 2024-04-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('total_number', models.PositiveIntegerField(default=0)),
                ('buy_now', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('marka', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField(default=0)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('with_photo', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=64)),
                ('volume', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
