# Generated by Django 4.2.8 on 2024-04-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.FloatField(),
        ),
    ]
